name: Terraform Apply (on main branch push)

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform Plan
        run: |
          terraform plan \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=${{ secrets.GCP_REGION }}"
             -var="service_account_email=${{ secrets.GCP_SA_EMAIL }}"

      - name: Apply Terraform Changes
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=${{ secrets.GCP_REGION }}"
             -var="service_account_email=${{ secrets.GCP_SA_EMAIL }}"
